### PR TITLE
Section for publications

### PR DESCRIPTION
**Pull request by epatters**
Look at those pubs! Once the ACSets paper is on arXiv, we'll add it too.

### CODE REVIEW

**Comment by epatters** [comment]
I also added the GReTA talk. @jpfairbanks, we should add your PDF slides to `assets/slides` and link them from the main page.

**Comment by mehalter** [comment]
Should we add our ACT paper from 2020 as well? https://arxiv.org/abs/2005.04831

**Comment by epatters** [comment]
Sure, I'll add it.

**Comment by epatters** [comment]
We'll have the ACSets paper on arXiv in a few days, but I'll go ahead and merge this one now.

**Pull request merged**
